"""Write schema/vocab.csv — the vocabulary seed.

Run: uv run python scripts/seed_vocab.py

Columns: kind, slug, canonical, aliases, implies, ambiguous, context, description
  kind        skill | topic
  aliases     '|'-separated surface forms (the canonical is always a surface form too)
  implies     '|'-separated slugs: a document tagged with this term is also tagged with those
  ambiguous   surface forms that count only with context (ordinary words: Phoenix, Spark, Go, R, Excel …)
  context     '|'-separated words; an ambiguous form counts when one of these occurs in the same section,
              or when any non-ambiguous form of the same term occurs anywhere in the document
  description one sentence, embedded for the semantic ("weak") channel; skills get a generated one

The script refuses to write when a surface form belongs to two terms or an implication
target does not exist.
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

# (slug, canonical, aliases, implies, ambiguous, context)   — skills
S: list[tuple] = [
    # --- languages
    ("python", "Python", "Python 3", "", "", ""),
    ("java", "Java", "Java 8|Java 11|Java 17|Core Java", "", "", ""),
    ("javascript", "JavaScript", "JS|ES6|ECMAScript|Javascript", "", "JS", "javascript|html|node|react|typescript|web|frontend|css"),
    ("typescript", "TypeScript", "TS", "", "TS", "typescript|javascript|react|angular|node|frontend"),
    ("c", "C", "C programming|ANSI C|C language|C/C++|Embedded C", "", "C", "embedded|firmware|c++|gcc|kernel|microcontroller|pointers|systems|linux|rtos"),
    ("cpp", "C++", "cpp|C++11|C++17|Modern C++", "", "", ""),
    ("csharp", "C#", "C sharp|csharp", "", "", ""),
    ("go", "Go", "Golang|Go language|Go lang", "", "Go", "golang|goroutine|goroutines|go-lang|gin|gorm|go modules|go services|grpc"),
    ("rust", "Rust", "Rust language|rustlang", "", "Rust", "cargo|tokio|wasm|rustlang|crates|systems programming|memory safety|borrow checker"),
    ("ruby", "Ruby", "Ruby language", "", "Ruby", "rails|gem|gems|sinatra|rspec|programming|backend|rake"),
    ("php", "PHP", "PHP 7|PHP 8", "", "", ""),
    ("perl", "Perl", "", "", "", ""),
    ("scala", "Scala", "", "", "", ""),
    ("kotlin", "Kotlin", "", "", "", ""),
    ("swift", "Swift", "Swift language|Swift 5", "", "Swift", "ios|xcode|swiftui|apple|objective-c|app|mobile|iphone|cocoa"),
    ("objective-c", "Objective-C", "ObjC|Objective C", "", "", ""),
    ("dart", "Dart", "Dart language", "", "Dart", "flutter|mobile|widgets|android|ios"),
    ("elixir", "Elixir", "Elixir language|Elixir/OTP|OTP", "", "OTP", "elixir|erlang|phoenix|beam|genserver"),
    ("erlang", "Erlang", "BEAM VM", "", "", ""),
    ("haskell", "Haskell", "", "", "", ""),
    ("clojure", "Clojure", "ClojureScript", "", "", ""),
    ("fsharp", "F#", "", "", "", ""),
    ("r", "R", "R language|R programming|RStudio|tidyverse|dplyr|ggplot2|Shiny", "", "R", "rstudio|tidyverse|ggplot|ggplot2|dplyr|cran|shiny|sas|spss|statistical|regression"),
    ("matlab", "MATLAB", "Simulink", "", "", ""),
    ("sql", "SQL", "T-SQL|PL/SQL|SQL queries|stored procedures|SQL scripting", "", "", ""),
    ("bash", "Bash", "shell scripting|bash scripting|shell scripts|Unix shell", "", "", ""),
    ("powershell", "PowerShell", "", "", "", ""),
    ("vba", "VBA", "Visual Basic|Excel macros|VBA macros", "", "", ""),
    ("groovy", "Groovy", "", "", "", ""),
    ("lua", "Lua", "", "", "", ""),
    ("cobol", "COBOL", "", "", "", ""),
    ("fortran", "Fortran", "", "", "", ""),
    ("assembly", "assembly language", "assembler|x86 assembly|ARM assembly", "embedded-firmware", "", ""),
    ("solidity", "Solidity", "", "blockchain", "", ""),
    ("sas", "SAS", "SAS programming|Base SAS", "", "", ""),
    ("stata", "Stata", "", "", "", ""),
    ("spss", "SPSS", "", "", "", ""),
    ("julia", "Julia", "Julia language", "", "Julia", "programming|scientific computing|numerical|python|jupyter"),
    ("abap", "ABAP", "SAP ABAP", "sap", "", ""),
    # --- backend frameworks & protocols
    ("spring", "Spring Framework", "Spring Boot|Spring MVC|Spring Data|Spring Security|Spring Cloud|Spring|Spring Batch", "java", "Spring", "java|boot|hibernate|maven|microservices|jpa|mvc|rest|gradle|kotlin"),
    ("hibernate", "Hibernate", "JPA|Hibernate ORM", "java", "", ""),
    ("java-ee", "Java EE", "J2EE|Jakarta EE|JEE|EJB|servlets|JSP", "java", "", ""),
    ("maven", "Maven", "Apache Maven|Gradle|Ant build", "java", "Maven", "java|build|gradle|pom|jenkins|ant|dependencies|artifacts|spring"),
    ("junit", "JUnit", "JUnit 5|TestNG|Mockito|unit tests in Java", "java", "", ""),
    ("pytest", "pytest", "unittest|pytest fixtures|tox", "python", "", ""),
    ("rspec", "RSpec", "Minitest|Capybara", "ruby", "", ""),
    ("dotnet", ".NET", ".NET Core|.NET Framework|ASP.NET|ASP.NET Core|dotnet|ASP.NET MVC|.NET 6|.NET 8", "", "", ""),
    ("entity-framework", "Entity Framework", "EF Core", "dotnet", "", ""),
    ("wpf", "WPF", "WinForms|Windows Forms", "dotnet", "", ""),
    ("blazor", "Blazor", "", "dotnet", "", ""),
    ("django", "Django", "Django REST Framework|DRF", "python", "", ""),
    ("flask", "Flask", "", "python", "Flask", "python|api|rest|web|sqlalchemy|gunicorn"),
    ("fastapi", "FastAPI", "", "python", "", ""),
    ("rails", "Ruby on Rails", "Rails|RoR", "ruby", "Rails", "ruby|activerecord|gem|rspec|web|sidekiq"),
    ("laravel", "Laravel", "", "php", "", ""),
    ("symfony", "Symfony", "", "php", "", ""),
    ("express", "Express.js", "Express|ExpressJS", "nodejs", "Express", "node|node.js|javascript|middleware|api|npm|typescript|backend"),
    ("nodejs", "Node.js", "NodeJS|Node|npm", "javascript", "Node", "javascript|npm|express|typescript|backend|server|api|react"),
    ("nestjs", "NestJS", "Nest.js", "nodejs", "", ""),
    ("phoenix-framework", "Phoenix Framework", "Phoenix|Phoenix LiveView|LiveView", "elixir", "Phoenix", "elixir|erlang|liveview|ecto|otp|beam|genserver"),
    ("ecto", "Ecto", "", "elixir", "", ""),
    ("gin", "Gin", "Gin framework", "go", "Gin", "go|golang|http|api|middleware"),
    ("grpc", "gRPC", "", "", "", ""),
    ("graphql", "GraphQL", "Apollo GraphQL|Apollo", "", "Apollo", "graphql|schema|resolvers|api|react|queries|mutations"),
    ("rest-apis", "REST APIs", "REST|RESTful|REST API|RESTful APIs|web services|web service|HTTP APIs|HTTP API|RESTful services|RESTful web services|API development", "", "", ""),
    ("soap", "SOAP", "SOAP web services|WSDL", "", "SOAP", "wsdl|xml|web services|api|wcf|java|integration|endpoint"),
    ("websockets", "WebSockets", "WebSocket|Socket.IO", "", "", ""),
    ("openapi", "OpenAPI", "Swagger", "", "", ""),
    ("protobuf", "Protocol Buffers", "protobuf|Protobuf", "", "", ""),
    ("oauth", "OAuth 2.0", "OAuth|OAuth2|OIDC|OpenID Connect", "identity", "", ""),
    ("saml", "SAML", "SAML 2.0", "identity", "", ""),
    ("jwt", "JWT", "JSON Web Tokens", "identity", "", ""),
    ("keycloak", "Keycloak", "", "identity", "", ""),
    ("okta", "Okta", "", "identity", "", ""),
    ("auth0", "Auth0", "", "identity", "", ""),
    ("active-directory", "Active Directory", "AD|Azure AD|Entra ID|Group Policy", "", "AD", "windows|directory|group policy|users|domain|server|accounts|exchange"),
    ("ldap", "LDAP", "OpenLDAP", "", "", ""),
    # --- frontend & mobile
    ("react", "React", "React.js|ReactJS|React JS|Redux|Hooks", "web-development", "React|Hooks", "javascript|typescript|redux|jsx|next.js|frontend|front-end|components|web|css|html|node|ui"),
    ("nextjs", "Next.js", "NextJS", "react", "", ""),
    ("vue", "Vue.js", "Vue|VueJS|Nuxt|Vuex", "web-development", "Vue", "javascript|frontend|components|vuex|nuxt|typescript|web"),
    ("angular", "Angular", "AngularJS|Angular 2+|Angular CLI", "web-development", "", ""),
    ("svelte", "Svelte", "SvelteKit", "web-development", "", ""),
    ("jquery", "jQuery", "", "web-development", "", ""),
    ("html", "HTML", "HTML5", "web-development", "", ""),
    ("css", "CSS", "CSS3|SCSS|Sass", "web-development", "", ""),
    ("tailwind", "Tailwind CSS", "Tailwind", "css", "", ""),
    ("bootstrap", "Bootstrap", "Bootstrap 5", "css", "Bootstrap", "css|html|responsive|frontend|jquery|web|grid"),
    ("webpack", "Webpack", "Vite|Rollup|Babel", "javascript", "", ""),
    ("storybook", "Storybook", "", "design-systems", "", ""),
    ("jest", "Jest", "Mocha|Vitest", "test-automation", "Jest", "javascript|testing|react|unit tests|typescript|mocha|coverage"),
    ("cypress", "Cypress", "", "test-automation", "Cypress", "testing|e2e|end-to-end|javascript|selenium|automation|qa|browser"),
    ("playwright", "Playwright", "", "test-automation", "Playwright", "testing|e2e|browser|automation|qa|selenium|typescript"),
    ("selenium", "Selenium", "Selenium WebDriver|WebDriver", "test-automation", "", ""),
    ("appium", "Appium", "", "test-automation", "", ""),
    ("react-native", "React Native", "", "mobile-apps", "", ""),
    ("flutter", "Flutter", "", "mobile-apps", "Flutter", "dart|mobile|android|ios|app|widgets"),
    ("swiftui", "SwiftUI", "UIKit", "mobile-apps", "", ""),
    ("jetpack-compose", "Jetpack Compose", "Android Jetpack", "mobile-apps", "", ""),
    ("android", "Android", "Android SDK|Android development|Android Studio", "mobile-apps", "", ""),
    ("ios", "iOS", "iOS development|iPhone apps|iOS SDK|iPadOS", "mobile-apps", "", ""),
    ("xcode", "Xcode", "TestFlight", "ios", "", ""),
    ("xamarin", "Xamarin", ".NET MAUI", "mobile-apps", "", ""),
    ("firebase", "Firebase", "Firestore", "", "", ""),
    ("electron", "Electron", "", "", "Electron", "desktop|javascript|node|app|cross-platform"),
    ("unity", "Unity", "Unity3D|Unity Engine", "game-development", "Unity", "c#|game|3d|engine|unreal|gameplay|assets|shaders"),
    ("unreal", "Unreal Engine", "UE4|UE5", "game-development", "", ""),
    ("godot", "Godot", "", "game-development", "", ""),
    # --- data, ML, analytics
    ("pandas", "pandas", "", "python", "", ""),
    ("numpy", "NumPy", "SciPy", "python", "", ""),
    ("scikit-learn", "scikit-learn", "sklearn|scikit learn", "machine-learning", "", ""),
    ("pytorch", "PyTorch", "", "machine-learning", "", ""),
    ("tensorflow", "TensorFlow", "Keras", "machine-learning", "", ""),
    ("xgboost", "XGBoost", "LightGBM|CatBoost|gradient boosting", "machine-learning", "", ""),
    ("hugging-face", "Hugging Face", "HuggingFace|transformers library", "nlp", "", ""),
    ("langchain", "LangChain", "LlamaIndex", "nlp", "", ""),
    ("openai-api", "OpenAI API", "GPT-4|GPT-3|ChatGPT API|LLM APIs|prompt engineering", "nlp", "", ""),
    ("spacy", "spaCy", "NLTK", "nlp", "", ""),
    ("opencv", "OpenCV", "", "computer-vision", "", ""),
    ("cuda", "CUDA", "cuDNN", "", "", ""),
    ("mlflow", "MLflow", "", "ml-ops", "", ""),
    ("kubeflow", "Kubeflow", "", "ml-ops", "", ""),
    ("sagemaker", "Amazon SageMaker", "SageMaker", "ml-ops", "", ""),
    ("vertex-ai", "Vertex AI", "", "ml-ops", "", ""),
    ("jupyter", "Jupyter", "Jupyter notebooks|Google Colab", "python", "", ""),
    ("matplotlib", "Matplotlib", "Seaborn|Plotly", "python", "", ""),
    ("streamlit", "Streamlit", "Gradio|Dash", "python", "Dash", "python|streamlit|plotly|app|dashboard"),
    ("tableau", "Tableau", "Tableau Desktop|Tableau Server", "business-intelligence", "", ""),
    ("power-bi", "Power BI", "PowerBI|DAX|Power Query", "business-intelligence", "", ""),
    ("looker", "Looker", "LookML|Looker Studio|Data Studio", "business-intelligence", "", ""),
    ("qlik", "Qlik", "QlikView|Qlik Sense", "business-intelligence", "", ""),
    ("cognos", "IBM Cognos", "Cognos", "business-intelligence", "", ""),
    ("microstrategy", "MicroStrategy", "", "business-intelligence", "", ""),
    ("ssrs", "SSRS", "SQL Server Reporting Services|Crystal Reports", "business-intelligence", "", ""),
    ("ssis", "SSIS", "SQL Server Integration Services", "data-pipelines", "", ""),
    ("informatica", "Informatica", "Informatica PowerCenter", "data-pipelines", "", ""),
    ("talend", "Talend", "Pentaho|Matillion", "data-pipelines", "", ""),
    ("airflow", "Apache Airflow", "Airflow|Airflow DAGs", "data-pipelines", "Airflow", "dag|dags|python|etl|pipeline|pipelines|scheduler|data|orchestration|workflows|dbt|spark"),
    ("dbt", "dbt", "dbt models|data build tool", "data-pipelines", "dbt", "sql|models|warehouse|snowflake|bigquery|redshift|data|transformations|analytics|airflow|pipeline"),
    ("spark", "Apache Spark", "Spark|PySpark|Spark SQL|Spark Streaming", "data-pipelines", "Spark", "pyspark|hadoop|databricks|scala|spark sql|rdd|dataframes|emr|hive|big data"),
    ("kafka", "Apache Kafka", "Kafka|Kafka Streams|event streaming", "", "", ""),
    ("kafka-connect", "Kafka Connect", "Debezium", "data-pipelines", "", ""),
    ("flink", "Apache Flink", "Flink", "data-pipelines", "", ""),
    ("dagster", "Dagster", "", "data-pipelines", "", ""),
    ("prefect", "Prefect", "", "data-pipelines", "Prefect", "python|orchestration|flows|data|pipeline|airflow|dagster"),
    ("fivetran", "Fivetran", "Stitch|Airbyte", "data-pipelines", "", ""),
    ("etl", "ETL", "ELT|extract transform load|ETL development|ETL jobs|ETL processes|ETL workflows", "data-pipelines", "", ""),
    ("hadoop", "Hadoop", "HDFS|MapReduce|YARN|Cloudera|Hortonworks", "", "", ""),
    ("hive", "Apache Hive", "Hive|HiveQL|Impala", "hadoop", "Hive", "hadoop|sql|spark|big data|hdfs|impala|data|tables|queries"),
    ("snowflake", "Snowflake", "", "data-warehousing", "Snowflake", "sql|warehouse|data|dbt|cloud|etl|tables|queries|schema|analytics"),
    ("bigquery", "BigQuery", "", "data-warehousing", "", ""),
    ("redshift", "Amazon Redshift", "Redshift", "data-warehousing", "", ""),
    ("databricks", "Databricks", "Delta Lake|Unity Catalog", "data-warehousing", "", ""),
    ("synapse", "Azure Synapse", "Azure Data Factory|ADF", "data-pipelines", "ADF", "azure|data|synapse|pipeline|etl"),
    ("teradata", "Teradata", "", "data-warehousing", "", ""),
    ("oracle-db", "Oracle Database", "Oracle|Oracle DB|Oracle 11g|Oracle 12c|Oracle 19c|Oracle RAC|Oracle SQL", "", "", ""),
    ("sql-server", "SQL Server", "MS SQL|MSSQL|Microsoft SQL Server|SQL Server 2019", "", "", ""),
    ("mysql", "MySQL", "MariaDB", "", "", ""),
    ("postgresql", "PostgreSQL", "Postgres|PostGIS", "", "", ""),
    ("mongodb", "MongoDB", "Mongo|Mongoose", "", "", ""),
    ("redis", "Redis", "", "", "", ""),
    ("cassandra", "Apache Cassandra", "Cassandra|ScyllaDB", "", "Cassandra", "nosql|database|cql|cluster|keyspace|scylla|distributed"),
    ("dynamodb", "DynamoDB", "", "aws", "", ""),
    ("elasticsearch", "Elasticsearch", "Elastic Search|ELK|Elastic Stack|OpenSearch|Kibana|Logstash", "search", "", ""),
    ("solr", "Apache Solr", "Solr|Lucene", "search", "", ""),
    ("algolia", "Algolia", "Meilisearch|Typesense", "search", "", ""),
    ("neo4j", "Neo4j", "Cypher|graph database", "", "", ""),
    ("sqlite", "SQLite", "", "", "", ""),
    ("couchbase", "Couchbase", "CouchDB", "", "", ""),
    ("db2", "IBM DB2", "DB2", "", "", ""),
    ("ms-access", "Microsoft Access", "MS Access|Access database|Access", "", "Access", "microsoft|ms office|office|excel|word|outlook|vba"),
    ("rabbitmq", "RabbitMQ", "AMQP|ActiveMQ|message queue|message queues", "", "", ""),
    ("vector-database", "vector database", "Pinecone|Weaviate|pgvector|FAISS|vector search|Milvus|Qdrant|Chroma", "search", "", ""),
    # --- cloud, containers, devops
    ("aws", "AWS", "Amazon Web Services|EC2|S3|AWS Lambda|RDS|CloudFormation|EKS|ECS|CloudWatch|SQS|SNS|VPC|Route 53", "cloud-migration", "", ""),
    ("azure", "Microsoft Azure", "Azure|Azure DevOps|Azure Functions|AKS|Azure Pipelines|Azure Kubernetes Service", "cloud-migration", "", ""),
    ("gcp", "Google Cloud", "GCP|Google Cloud Platform|GKE|Cloud Run|Pub/Sub|Cloud Functions", "cloud-migration", "", ""),
    ("docker", "Docker", "Docker Compose|containers|containerization|containerized", "", "", ""),
    ("kubernetes", "Kubernetes", "k8s|OpenShift|kubectl", "kubernetes-platform", "", ""),
    ("helm", "Helm", "Helm charts", "kubernetes-platform", "Helm", "kubernetes|k8s|charts|deploy|containers|cluster|argo"),
    ("terraform", "Terraform", "Terragrunt|OpenTofu", "devops", "", ""),
    ("pulumi", "Pulumi", "", "devops", "", ""),
    ("ansible", "Ansible", "Ansible playbooks", "devops", "", ""),
    ("puppet", "Puppet", "SaltStack", "devops", "Puppet", "ansible|chef|configuration management|devops|servers|automation|linux|infrastructure"),
    ("vagrant", "Vagrant", "Packer", "devops", "", ""),
    ("jenkins", "Jenkins", "Jenkins pipelines", "ci-cd", "", ""),
    ("github-actions", "GitHub Actions", "", "ci-cd", "", ""),
    ("gitlab-ci", "GitLab CI", "GitLab CI/CD|GitLab pipelines", "ci-cd", "", ""),
    ("circleci", "CircleCI", "Travis CI|TeamCity", "ci-cd", "", ""),
    ("argocd", "Argo CD", "ArgoCD|Argo Workflows|Flux CD|GitOps", "ci-cd", "", ""),
    ("octopus-deploy", "Octopus Deploy", "", "ci-cd", "", ""),
    ("git", "Git", "GitHub|GitLab|Bitbucket|version control|source control|Git workflows", "", "", ""),
    ("svn", "Subversion", "SVN|Perforce|TFS", "", "", ""),
    ("prometheus", "Prometheus", "Alertmanager|Thanos", "observability", "", ""),
    ("grafana", "Grafana", "Loki|Tempo", "observability", "", ""),
    ("datadog", "Datadog", "", "observability", "", ""),
    ("new-relic", "New Relic", "AppDynamics|Dynatrace", "observability", "", ""),
    ("splunk", "Splunk", "", "observability", "", ""),
    ("opentelemetry", "OpenTelemetry", "Jaeger|Zipkin|distributed tracing", "observability", "", ""),
    ("pagerduty", "PagerDuty", "Opsgenie|on-call rotation|on-call", "devops", "", ""),
    ("nagios", "Nagios", "Zabbix|Icinga|SolarWinds", "observability", "", ""),
    ("linux", "Linux", "Ubuntu|RHEL|Red Hat|CentOS|Debian|Unix|Linux administration|Linux servers", "", "", ""),
    ("windows-server", "Windows Server", "Windows Server 2016|Windows Server 2019|Windows Server 2022|Windows administration|Microsoft Exchange|Exchange Server", "", "", ""),
    ("macos", "macOS", "Mac OS|OS X", "", "", ""),
    ("vmware", "VMware", "vSphere|ESXi|vCenter|virtualization", "", "", ""),
    ("hyper-v", "Hyper-V", "", "", "", ""),
    ("citrix", "Citrix", "XenApp|XenDesktop|VDI", "", "", ""),
    ("nginx", "Nginx", "HAProxy|load balancers|load balancing", "", "", ""),
    ("apache-httpd", "Apache HTTP Server", "Apache HTTP|httpd|Apache web server|Apache", "", "Apache", "http|web server|nginx|tomcat|httpd|php|linux|mod_|vhost|hosting"),
    ("tomcat", "Apache Tomcat", "Tomcat", "java", "", ""),
    ("iis", "IIS", "Internet Information Services", "windows-server", "", ""),
    ("weblogic", "WebLogic", "WebSphere|JBoss|WildFly", "java", "", ""),
    ("heroku", "Heroku", "Render|Fly.io", "", "", ""),
    ("vercel", "Vercel", "Netlify", "", "", ""),
    ("cloudflare", "Cloudflare", "CDN|Akamai|Fastly", "", "", ""),
    ("serverless", "serverless", "FaaS|serverless architecture", "", "", ""),
    ("istio", "Istio", "service mesh|Envoy|Linkerd", "kubernetes-platform", "", ""),
    ("vault", "HashiCorp Vault", "HashiCorp Consul|Consul", "devops", "Consul", "hashicorp|vault|service discovery|terraform|kubernetes"),
    ("cisco", "Cisco", "Cisco IOS|Cisco routers|Cisco switches|CCNA|CCNP|CCIE|Cisco Meraki", "networking", "", ""),
    ("juniper", "Juniper Networks", "Juniper|Junos", "networking", "Juniper", "cisco|network|router|junos|switch|firewall|routing|bgp"),
    ("palo-alto", "Palo Alto Networks", "Palo Alto firewalls|Fortinet|FortiGate|Check Point", "networking", "", ""),
    ("firewalls", "firewalls", "firewall administration|network firewalls|Cisco ASA|firewall rules", "networking", "", ""),
    ("vpn", "VPN", "IPsec|site-to-site VPN|remote access VPN", "networking", "", ""),
    ("tcp-ip", "TCP/IP", "DNS|DHCP|subnetting|VLAN|VLANs|BGP|OSPF|MPLS|routing protocols|LAN|WAN", "networking", "", ""),
    ("wireshark", "Wireshark", "packet capture|tcpdump", "networking", "", ""),
    ("nessus", "Nessus", "Qualys|Rapid7|vulnerability scanning", "security-operations", "", ""),
    ("metasploit", "Metasploit", "Kali Linux|Nmap", "appsec", "", ""),
    ("burp-suite", "Burp Suite", "Burp|OWASP ZAP", "appsec", "", ""),
    ("owasp", "OWASP", "OWASP Top 10|secure coding practices", "appsec", "", ""),
    ("siem", "SIEM", "Splunk Enterprise Security|QRadar|Microsoft Sentinel|ArcSight|Elastic SIEM", "security-operations", "", ""),
    ("crowdstrike", "CrowdStrike", "EDR|endpoint detection|SentinelOne|Carbon Black", "security-operations", "", ""),
    ("sonarqube", "SonarQube", "static analysis|SAST|DAST|Snyk|Checkmarx", "appsec", "", ""),
    # --- collaboration, business software
    ("jira", "Jira", "Atlassian Jira|Jira Software", "", "", ""),
    ("confluence", "Confluence", "", "", "", ""),
    ("trello", "Trello", "Asana|Monday.com|Basecamp|ClickUp", "", "", ""),
    ("servicenow", "ServiceNow", "", "", "", ""),
    ("zendesk", "Zendesk", "Freshdesk|Intercom", "customer-service", "", ""),
    ("salesforce", "Salesforce", "SFDC|Salesforce.com|Salesforce CRM|Sales Cloud|Service Cloud|Salesforce administration", "crm", "", ""),
    ("hubspot", "HubSpot", "HubSpot CRM", "crm", "", ""),
    ("dynamics-365", "Microsoft Dynamics", "Dynamics 365|Dynamics CRM|Dynamics AX|Dynamics NAV|Dynamics GP|Great Plains", "erp-implementation", "", ""),
    ("sap", "SAP", "SAP ERP|SAP FI/CO|SAP FICO|SAP MM|SAP SD|SAP HANA|S/4HANA|SAP BW|SAP PP|SAP HCM|SAP SuccessFactors|SuccessFactors|SAP Basis|SAP R/3", "erp-implementation", "", ""),
    ("oracle-ebs", "Oracle E-Business Suite", "Oracle EBS|Oracle Fusion|Oracle ERP|Oracle Financials|Oracle Apps|JD Edwards|Hyperion|Essbase", "erp-implementation", "", ""),
    ("netsuite", "NetSuite", "", "erp-implementation", "", ""),
    ("peoplesoft", "PeopleSoft", "PeopleSoft HCM", "hr-operations", "", ""),
    ("workday", "Workday", "Workday HCM", "hr-operations", "Workday", "hris|hcm|payroll|peoplesoft|sap|implementation|hr|benefits|onboarding|reporting"),
    ("adp", "ADP", "ADP Workforce Now|ADP payroll|ADP Vantage", "payroll", "", ""),
    ("kronos", "Kronos", "UKG|Ceridian|Dayforce|Paychex|Paylocity|Paycom", "payroll", "", ""),
    ("taleo", "Taleo", "iCIMS|applicant tracking system|ATS|Greenhouse ATS|Lever ATS|Workable|Bullhorn|Jobvite", "recruiting", "ATS", "recruiting|candidates|applicant|hiring|requisition|sourcing|resumes|job postings"),
    ("linkedin-recruiter", "LinkedIn Recruiter", "Boolean search|Indeed", "recruiting", "", ""),
    ("bamboohr", "BambooHR", "Gusto|Zenefits|Namely|Rippling", "hr-operations", "", ""),
    ("quickbooks", "QuickBooks", "QuickBooks Online|QBO", "accounting", "", ""),
    ("xero", "Xero", "FreshBooks|Wave accounting", "accounting", "", ""),
    ("sage", "Sage", "Sage 50|Sage 100|Sage 300|Sage Intacct|Peachtree", "accounting", "Sage", "accounting|payroll|ledger|invoices|quickbooks|bookkeeping|reconciliation|financial"),
    ("excel", "Microsoft Excel", "Excel|MS Excel|Excel 2016|Excel 2019|pivot tables|VLOOKUP|advanced Excel|Excel spreadsheets|spreadsheets|Excel modeling", "", "Excel", "microsoft|office|word|powerpoint|spreadsheet|spreadsheets|pivot|vlookup|macros|formulas|outlook|workbooks"),
    ("word", "Microsoft Word", "Word|MS Word", "", "Word", "microsoft|office|excel|powerpoint|outlook|typing|wpm"),
    ("powerpoint", "Microsoft PowerPoint", "PowerPoint|Power Point|PPT|MS PowerPoint", "", "", ""),
    ("outlook", "Microsoft Outlook", "Outlook", "", "Outlook", "microsoft|office|email|calendar|excel|word|exchange|scheduling"),
    ("microsoft-office", "Microsoft Office", "MS Office|MS Office Suite|Office 365|Microsoft 365|Office Suite|Microsoft Office Suite|Microsoft Publisher", "", "", ""),
    ("lotus-notes", "Lotus Notes", "IBM Notes|HCL Notes|Lotus Domino", "", "", ""),
    ("acrobat", "Adobe Acrobat", "Acrobat Pro|PDF editing", "", "", ""),
    ("windows", "Microsoft Windows", "Windows|Windows 7|Windows 10|Windows 11|Windows XP|Windows OS", "", "Windows", "microsoft|linux|mac|macos|operating system|operating systems|desktop|pc|workstation|active directory|os"),
    ("xml", "XML", "XSLT|XPath|XSD", "", "", ""),
    ("visual-studio", "Visual Studio", "VS Code|Visual Studio Code|VSCode", "", "", ""),
    ("ibm-i", "IBM i", "AS400|AS/400|iSeries|IBM iSeries|RPG", "", "RPG", "as400|iseries|ibm|cobol|mainframe"),
    ("businessobjects", "SAP BusinessObjects", "Business Objects|BusinessObjects|BOBJ|Web Intelligence", "business-intelligence", "", ""),
    ("dreamweaver", "Adobe Dreamweaver", "Dreamweaver", "web-development", "", ""),
    ("data-entry", "data entry", "data-entry|10-key|10 key|data entry clerk", "", "", ""),
    ("typing", "typing", "touch typing|wpm|words per minute|keyboarding", "", "", ""),
    ("amplitude", "Amplitude", "Mixpanel|Amplitude Analytics|product analytics", "analytics", "Amplitude", "analytics|product|events|funnels|mixpanel|segment|dashboards|retention|cohorts"),
    ("ab-testing", "A/B testing", "AB testing|split testing|experimentation|A/B tests|multivariate testing", "", "", ""),
    ("okrs", "OKRs", "OKR|objectives and key results", "", "", ""),
    ("jmeter", "JMeter", "Apache JMeter|Gatling|k6|Locust|load testing tools", "test-automation", "", ""),
    ("postman", "Postman", "Insomnia|API testing", "", "Postman", "api|rest|apis|endpoints|collections|testing|http|graphql"),
    ("fastlane", "Fastlane", "", "mobile-apps", "", ""),
    ("google-workspace", "Google Workspace", "G Suite|Google Docs|Google Sheets|Google Drive|Google Apps", "", "", ""),
    ("sharepoint", "SharePoint", "OneDrive", "", "", ""),
    ("visio", "Visio", "Lucidchart|draw.io|diagrams", "", "", ""),
    ("ms-project", "Microsoft Project", "MS Project|Primavera|Smartsheet|Gantt charts", "project-management", "", ""),
    ("teams", "Microsoft Teams", "Webex|Zoom meetings|Slack", "", "", ""),
    ("figma", "Figma", "FigJam", "ux-design", "", ""),
    ("sketch", "Sketch", "Sketch app", "ux-design", "Sketch", "figma|ui|ux|design|prototype|wireframes|invision|zeplin"),
    ("adobe-xd", "Adobe XD", "InVision|Zeplin|Axure|Balsamiq", "ux-design", "", ""),
    ("photoshop", "Adobe Photoshop", "Photoshop|Adobe Creative Suite|Creative Cloud|Adobe Creative Cloud", "graphic-design", "", ""),
    ("illustrator", "Adobe Illustrator", "Illustrator", "graphic-design", "Illustrator", "adobe|photoshop|indesign|vector|design|graphics|logos|creative suite"),
    ("indesign", "Adobe InDesign", "InDesign|QuarkXPress", "graphic-design", "", ""),
    ("after-effects", "Adobe After Effects", "After Effects", "media-production", "", ""),
    ("premiere", "Adobe Premiere", "Premiere Pro", "media-production", "", ""),
    ("lightroom", "Adobe Lightroom", "Lightroom|Capture One", "media-production", "", ""),
    ("final-cut", "Final Cut Pro", "Final Cut|DaVinci Resolve|Avid Media Composer", "media-production", "", ""),
    ("pro-tools", "Pro Tools", "Logic Pro|Ableton|Audacity", "media-production", "", ""),
    ("blender", "Blender", "", "media-production", "Blender", "3d|modeling|animation|render|rendering|maya|unity|sculpting|rigging"),
    ("maya", "Autodesk Maya", "Maya|3ds Max|Cinema 4D|ZBrush|Houdini", "media-production", "Maya", "3d|animation|autodesk|modeling|rigging|blender|render|vfx|texturing"),
    ("canva", "Canva", "", "graphic-design", "", ""),
    ("autocad", "AutoCAD", "AutoCAD Civil 3D|Civil 3D|MicroStation|CAD drafting|CAD", "engineering-design", "", ""),
    ("solidworks", "SolidWorks", "CATIA|Autodesk Inventor|PTC Creo|Pro/ENGINEER|Fusion 360|NX", "engineering-design", "", ""),
    ("revit", "Revit", "BIM|Navisworks|SketchUp|Bluebeam", "engineering-design", "", ""),
    ("arcgis", "ArcGIS", "GIS|QGIS|ESRI|geospatial", "", "", ""),
    ("labview", "LabVIEW", "", "engineering-design", "", ""),
    ("plc", "PLC programming", "PLC|PLCs|ladder logic|Allen-Bradley|Siemens PLC|Siemens TIA|RSLogix|SCADA|HMI", "manufacturing", "", ""),
    ("minitab", "Minitab", "JMP", "", "", ""),
    ("altium", "Altium Designer", "Altium|Eagle PCB|KiCad|OrCAD|Cadence Allegro", "engineering-design", "", ""),
    ("verilog", "Verilog", "VHDL|SystemVerilog|RTL design", "engineering-design", "", ""),
    ("fpga", "FPGA", "Xilinx|Intel FPGA|Vivado", "embedded-firmware", "", ""),
    ("arm-cortex", "ARM Cortex", "ARM Cortex-M|Cortex-M|ARM microcontrollers|STM32|ESP32|microcontrollers", "embedded-firmware", "", ""),
    ("freertos", "FreeRTOS", "", "embedded-firmware", "", ""),
    ("zephyr", "Zephyr", "Zephyr RTOS", "embedded-firmware", "Zephyr", "rtos|embedded|firmware|microcontroller|bluetooth|kernel|driver"),
    ("rtos", "RTOS", "real-time operating system|ThreadX|VxWorks|QNX", "embedded-firmware", "", ""),
    ("can-bus", "CAN bus", "CANopen|CAN protocol|LIN bus|automotive protocols", "embedded-firmware", "", ""),
    ("mqtt", "MQTT", "CoAP|LoRaWAN|Zigbee", "iot", "", ""),
    ("modbus", "Modbus", "OPC UA|Profinet|EtherCAT", "manufacturing", "", ""),
    ("i2c", "I2C", "SPI|UART|serial protocols|GPIO", "embedded-firmware", "", ""),
    ("ros", "ROS", "Robot Operating System|ROS2|ROS 2", "robotics", "ROS", "robot|robots|robotics|navigation|sensors|gazebo|slam|motion"),
    ("raspberry-pi", "Raspberry Pi", "Arduino|ESP8266|Jetson", "iot", "", ""),
    ("bluetooth", "Bluetooth", "BLE|Bluetooth Low Energy", "iot", "", ""),
    ("stripe", "Stripe", "", "payments", "", ""),
    ("adyen", "Adyen", "Braintree|Checkout.com", "payments", "", ""),
    ("paypal", "PayPal", "PayPal integration|Square payments", "payments", "", ""),
    ("twilio", "Twilio", "SendGrid|Vonage", "", "", ""),
    ("google-analytics", "Google Analytics", "GA4|Google Tag Manager", "digital-marketing", "", ""),
    ("google-ads", "Google Ads", "AdWords|Google AdWords|PPC|pay-per-click|Bing Ads", "digital-marketing", "", ""),
    ("facebook-ads", "Meta Ads", "Facebook Ads|Instagram Ads|Meta Business Suite|paid social", "digital-marketing", "", ""),
    ("seo", "SEO", "search engine optimization|search engine optimisation|keyword research|link building", "digital-marketing", "", ""),
    ("sem", "SEM", "search engine marketing", "digital-marketing", "SEM", "seo|google ads|ppc|marketing|campaigns|adwords|keywords|cpc"),
    ("mailchimp", "Mailchimp", "Constant Contact|Klaviyo|email campaigns", "digital-marketing", "", ""),
    ("marketo", "Marketo", "Pardot|Eloqua|marketing automation", "digital-marketing", "", ""),
    ("hootsuite", "Hootsuite", "Sprout Social|Buffer|Later", "social-media", "", ""),
    ("wordpress", "WordPress", "Drupal|Joomla|Wix|Squarespace|Webflow", "web-development", "", ""),
    ("shopify", "Shopify", "Shopify Plus", "e-commerce", "", ""),
    ("magento", "Magento", "Adobe Commerce|WooCommerce|BigCommerce|PrestaShop", "e-commerce", "", ""),
    ("amazon-seller", "Amazon Seller Central", "Amazon marketplace|Amazon FBA", "e-commerce", "", ""),
    ("epic", "Epic EHR", "Epic Systems|Epic", "patient-care", "Epic", "ehr|emr|cerner|healthcare|patient|hospital|charting|clinical|nursing"),
    ("cerner", "Cerner", "Meditech|Allscripts|athenahealth|eClinicalWorks|NextGen", "patient-care", "", ""),
    ("bloomberg", "Bloomberg Terminal", "Bloomberg|FactSet|Capital IQ|Refinitiv|Morningstar Direct", "investment", "", ""),
    ("gaap", "GAAP", "US GAAP|IFRS|ASC 606|ASC 842", "accounting", "", ""),
    ("sox", "SOX", "Sarbanes-Oxley|SOX 404", "auditing", "SOX", "sarbanes|compliance|audit|controls|internal|financial|section 404|coso|testing"),
    ("cpa", "CPA", "Certified Public Accountant|CMA|CIA certification|Enrolled Agent", "accounting", "", ""),
    ("cfa", "CFA", "Chartered Financial Analyst|Series 7|Series 63|FINRA", "investment", "", ""),
    ("pmp", "PMP", "Project Management Professional|PMI|PRINCE2|CAPM", "project-management", "", ""),
    ("cissp", "CISSP", "CISM|CISA|CEH|Security+|CompTIA Security+|OSCP|GIAC", "security-operations", "", ""),
    ("comptia", "CompTIA", "A+ certification|Network+|CompTIA A+|CompTIA Network+", "", "", ""),
    ("itil", "ITIL", "ITIL v3|ITIL 4|ITSM|IT service management", "", "", ""),
    ("six-sigma", "Six Sigma", "Lean Six Sigma|Green Belt|Black Belt|Six Sigma Green Belt|Six Sigma Black Belt|DMAIC", "", "", ""),
    ("lean", "Lean", "Lean manufacturing|Lean methodology|kaizen|5S|value stream mapping", "", "Lean", "six sigma|kaizen|manufacturing|continuous improvement|waste|5s|process improvement|toyota|production"),
    ("agile", "Agile", "Agile methodologies|Scrum|Kanban|Scrum Master|sprint planning|Agile/Scrum|CSM|Certified Scrum Master|Agile development", "", "Agile", "scrum|sprint|kanban|jira|software|development|team|methodology|backlog|standups|retrospectives|product owner"),
    ("osha", "OSHA", "OSHA 10|OSHA 30|OSHA certified|OSHA compliance|safety compliance", "", "", ""),
    ("cpr", "CPR", "BLS|ACLS|PALS|first aid|AED|CPR certified", "", "", ""),
    ("forklift", "forklift", "forklift certified|forklift operation|forklift operator|pallet jack|reach truck", "supply-chain", "", ""),
    ("cdl", "CDL", "commercial driver's license|Class A CDL|Class B CDL|CDL-A", "supply-chain", "", ""),
    ("pos-systems", "POS systems", "point of sale|POS|Square POS|Toast POS|Aloha POS|Micros", "", "POS", "register|cash|retail|restaurant|sales|store|transactions|customers|orders"),
    ("bilingual-spanish", "Spanish", "bilingual Spanish|fluent in Spanish|Spanish speaking|Spanish/English", "", "Spanish", "bilingual|fluent|language|languages|speak|translation|english"),
]

# (slug, canonical, aliases, ambiguous, context, description)   — topics (implies is never set on a topic)
T: list[tuple] = [
    ("data-pipelines", "data pipelines", "data pipeline|ETL pipelines|ETL pipeline|data ingestion|ingestion pipeline|ingestion pipelines|batch pipeline|batch pipelines|streaming pipeline|streaming pipelines|change data capture|CDC|data integration", "CDC",
     "data|kafka|debezium|replication|database|warehouse|tables|streams|etl|sql",
     "Worked on data pipelines: building and operating ETL/ELT jobs, ingestion jobs and nightly batch jobs that move data from source systems into a warehouse or lake, streaming jobs, change data capture, scheduled data loads, backfills of historical data, replicating tables between systems, transforming and loading data for downstream teams."),
    ("analytics", "analytics", "data analytics|analytics dashboards|reporting and analytics|data analysis|ad hoc analysis|metrics and reporting", "", "",
     "Analytics: dashboards, reports, metrics and ad-hoc analysis over business data to answer questions and support decisions."),
    ("ml-ops", "MLOps", "ML Ops|machine learning operations|model deployment|model serving|ML platform|model monitoring|feature store", "", "",
     "MLOps: deploying, serving, monitoring and retraining machine learning models in production, with pipelines and infrastructure around them."),
    ("observability", "observability", "monitoring and alerting|logging and metrics|tracing|SRE observability|application monitoring|infrastructure monitoring|alerting", "", "",
     "Observability: metrics, logs, traces, dashboards and alerting so engineers can see how systems behave and respond to incidents."),
    ("payments", "payments", "payment processing|payment systems|checkout|card payments|payment gateway|payment integration|billing systems|subscriptions billing", "", "",
     "Payments: processing card and bank payments, checkout flows, billing, invoicing systems, payment gateways and reconciliation of transactions."),
    ("search", "search", "search engine|search relevance|full-text search|site search|search ranking|search indexing|search functionality", "search", "relevance|ranking|elasticsearch|solr|lucene|indexing|query|queries|opensearch|algolia|index|results",
     "Search: building search engines and features — indexing, full-text and semantic retrieval, relevance ranking and query understanding."),
    ("identity", "authentication", "identity and access management|IAM|SSO|single sign-on|authorization|access management|identity management|user authentication|login system|access control", "", "",
     "Identity: authentication, authorization, single sign-on, OAuth/OIDC/SAML, user accounts, roles and access control."),
    ("api-platform", "API platform", "API design|public API|API gateway|developer platform|API strategy|platform APIs|API management", "", "",
     "API platform work: designing, versioning, documenting and operating APIs and gateways that other teams and customers build on."),
    ("design-systems", "design system", "design systems|component library|UI kit|pattern library|reusable components", "", "",
     "Design systems: shared UI component libraries, tokens, patterns and guidelines used across products."),
    ("accessibility", "accessibility", "a11y|WCAG|accessible design|screen reader|screen readers|ADA compliance|inclusive design", "", "",
     "Accessibility: making products usable by everyone — WCAG conformance, screen readers, keyboard navigation, inclusive design."),
    ("e-commerce", "e-commerce", "ecommerce|online store|online shop|storefront|checkout flow|retail platform|online sales|marketplace", "", "",
     "E-commerce: online stores and marketplaces — catalogues, carts, checkout, orders, fulfilment and merchandising."),
    ("kubernetes-platform", "Kubernetes platform", "container platform|container orchestration|cluster operations|cluster management", "", "",
     "Running a Kubernetes/container platform: clusters, deployments, networking, scaling and the tooling teams deploy with."),
    ("ci-cd", "CI/CD", "continuous integration|continuous delivery|continuous deployment|build pipeline|build pipelines|deployment pipeline|deployment pipelines|release automation|build automation|release management", "", "",
     "CI/CD: automated build, test and deployment pipelines and release processes for software."),
    ("recommendation", "recommendation systems", "recommender|recommendation engine|personalization|personalisation|recommendations", "recommendations", "model|ranking|personalization|collaborative|users|engagement|ml|algorithm|content|products",
     "Recommendation systems: personalised ranking and suggestions of products or content driven by user behaviour and models."),
    ("appsec", "application security", "AppSec|secure coding|security testing|penetration testing|pentesting|vulnerability management|threat modeling|security reviews|code security", "", "",
     "Application security: finding and fixing vulnerabilities, secure coding, threat modelling, penetration testing and security tooling."),
    ("embedded-firmware", "firmware", "embedded software|embedded systems|bare-metal|microcontroller programming|device drivers|embedded development", "", "",
     "Embedded software and firmware: code that runs on microcontrollers and devices, drivers, real-time constraints, hardware interfaces."),
    ("robotics", "robotics", "robot|robots|autonomous systems|motion planning|robotic systems|autonomous vehicles", "", "",
     "Robotics: software for robots and autonomous systems — perception, planning, control, simulation."),
    ("iot", "IoT", "internet of things|connected devices|sensor networks|edge devices|smart devices|telemetry", "", "",
     "IoT: connected devices and sensors, edge software, device telemetry, protocols and fleet management."),
    ("machine-learning", "machine learning", "ML models|deep learning|predictive modeling|model training|neural networks|AI models|predictive analytics|statistical modeling|classification models", "", "",
     "Machine learning: training and evaluating models — classification, regression, deep learning — and applying them to products and analysis."),
    ("nlp", "natural language processing", "NLP|text analytics|text mining|language models|LLM applications|large language models|chatbots|conversational AI|generative AI", "", "",
     "Natural language processing: text classification and extraction, language models, LLM-based applications, chatbots, search over text."),
    ("computer-vision", "computer vision", "image recognition|object detection|image processing|video analytics|OCR", "", "",
     "Computer vision: image and video understanding — detection, recognition, segmentation, OCR."),
    ("mobile-apps", "mobile apps", "mobile applications|iOS app|Android app|mobile development|app development|mobile app", "", "",
     "Mobile app development for iOS and Android: native or cross-platform apps, app store releases, mobile UX."),
    ("web-development", "web development", "web applications|web apps|frontend development|front-end development|websites|web design|web developer|single-page applications", "", "",
     "Web development: building websites and web applications — frontend UI, browser code, responsive layouts."),
    ("backend-services", "backend services", "backend development|back-end development|server-side|microservices|distributed systems|service architecture|backend systems", "", "",
     "Backend services: server-side systems, microservices, distributed systems, databases and the APIs between them."),
    ("cloud-migration", "cloud migration", "cloud infrastructure|cloud architecture|cloud adoption|migrated to the cloud|infrastructure as code|cloud platform|cloud services", "", "",
     "Cloud infrastructure and migration: architecting, provisioning and moving systems to AWS, Azure or Google Cloud, infrastructure as code."),
    ("devops", "DevOps", "platform engineering|site reliability|SRE|infrastructure automation|release engineering|DevOps practices|configuration management", "", "",
     "DevOps and SRE: automating infrastructure, deployments and operations; reliability, on-call, incident response, tooling for engineers."),
    ("data-warehousing", "data warehousing", "data warehouse|data lake|lakehouse|dimensional modeling|data modeling|star schema|data marts|OLAP", "", "",
     "Data warehousing: designing and maintaining warehouses and lakes, dimensional models, marts and the tables analysts query."),
    ("business-intelligence", "business intelligence", "BI|BI reporting|dashboards|KPI reporting|management reporting|executive dashboards|reporting tools", "", "",
     "Business intelligence: reports and dashboards for the business, KPIs, self-service analytics tools."),
    ("fraud-detection", "fraud detection", "fraud prevention|anti-money laundering|AML|risk scoring|fraud investigation|KYC|transaction monitoring", "", "",
     "Fraud and risk: detecting and preventing fraud, AML/KYC processes, transaction monitoring, risk models."),
    ("game-development", "game development", "gameplay|game engine|game design|video games|game programming", "", "",
     "Game development: gameplay systems, engines, graphics, tools and content for video games."),
    ("blockchain", "blockchain", "smart contracts|web3|DeFi|distributed ledger|crypto|cryptocurrency|Ethereum|NFT", "", "",
     "Blockchain: smart contracts, distributed ledgers, web3 and crypto applications."),
    ("networking", "networking", "network engineering|network administration|LAN/WAN|routing and switching|network infrastructure|network security|network operations", "networking", "router|routers|switch|switches|cisco|lan|wan|vpn|firewall|tcp|dns|infrastructure|bandwidth|subnets|wireless",
     "Computer networking: routers, switches, firewalls, VPNs, LAN/WAN design, network operations and troubleshooting."),
    ("security-operations", "security operations", "SOC|incident response|threat detection|cybersecurity|information security|SIEM monitoring|security monitoring|threat hunting|InfoSec", "", "",
     "Security operations: monitoring, detecting and responding to threats and incidents, SIEM, endpoint security, InfoSec programmes."),
    ("compliance", "compliance", "regulatory compliance|audit readiness|GDPR|HIPAA compliance|SOX compliance|policy compliance|compliance program|regulatory requirements", "", "",
     "Compliance: meeting regulatory and policy requirements — GDPR, HIPAA, SOX, PCI — audits, controls and documentation."),
    ("test-automation", "test automation", "automated testing|QA automation|end-to-end testing|regression testing|automated tests|test frameworks|unit testing|integration testing", "", "",
     "Test automation: automated unit, integration, end-to-end and regression testing, test frameworks and CI test suites."),
    ("performance-engineering", "performance engineering", "performance tuning|latency optimization|load testing|scalability|capacity planning|performance optimization|high availability|throughput", "", "",
     "Performance and scalability: profiling, tuning latency and throughput, load testing, capacity planning, high availability."),
    ("database-administration", "database administration", "DBA|database management|database tuning|backup and recovery|query optimization|database design|database migration|schema design", "", "",
     "Database administration: installing, tuning, backing up and securing databases; schema design, migrations, query optimisation."),
    ("erp-implementation", "ERP implementation", "ERP|ERP systems|SAP implementation|Oracle implementation|system implementation|ERP rollout|ERP migration|ERP support", "", "",
     "ERP systems: implementing, configuring and supporting SAP, Oracle, Dynamics or NetSuite for finance, supply chain and HR processes."),
    ("crm", "CRM", "customer relationship management|CRM systems|CRM implementation|CRM administration|CRM data", "", "",
     "CRM: customer relationship management systems such as Salesforce or HubSpot — configuration, data, workflows, reporting."),
    ("digital-marketing", "digital marketing", "online marketing|paid media|PPC campaigns|search marketing|performance marketing|social media marketing|email marketing|marketing campaigns|marketing analytics|growth marketing", "", "",
     "Digital marketing: paid search and social, SEO, email, campaign management, marketing analytics and growth."),
    ("content-marketing", "content marketing", "content strategy|copywriting|content creation|blog content|editorial|content calendar|technical writing", "", "",
     "Content: strategy, copywriting, editorial calendars, blogs and technical writing."),
    ("public-relations", "public relations", "PR|media relations|press releases|brand management|communications strategy|corporate communications|media outreach|publicity", "PR", "media|press|communications|brand|campaign|journalists|outreach|publicity|spokesperson|events",
     "Public relations and communications: media relations, press, brand messaging, corporate communications."),
    ("recruiting", "recruiting", "talent acquisition|recruitment|sourcing candidates|full-cycle recruiting|hiring|staffing|onboarding|candidate screening|interviewing candidates|job postings|headhunting", "", "",
     "Recruiting and talent acquisition: sourcing, screening, interviewing, hiring and onboarding candidates; staffing."),
    ("hr-operations", "HR operations", "human resources|HR generalist|employee relations|benefits administration|HRIS|performance management|HR policies|compensation and benefits|HR administration|workforce planning|employee engagement", "", "",
     "Human resources operations: employee relations, benefits, HRIS, policies, performance and compensation processes."),
    ("payroll", "payroll", "payroll processing|payroll administration|timekeeping|wage and hour|payroll taxes|garnishments", "", "",
     "Payroll: processing pay, timekeeping, deductions, taxes and payroll systems."),
    ("training-and-development", "training and development", "employee training|learning and development|L&D|curriculum development|instructional design|onboarding programs|coaching|mentoring|train the trainer|e-learning", "", "",
     "Training and development: designing and delivering training, instructional design, coaching, learning programmes."),
    ("accounting", "accounting", "general ledger|accounts payable|accounts receivable|bookkeeping|month-end close|reconciliations|financial statements|journal entries|fixed assets|bank reconciliations|invoicing|AP/AR|cost accounting", "", "",
     "Accounting: ledgers, AP/AR, reconciliations, month-end close, financial statements, bookkeeping."),
    ("financial-reporting", "financial reporting", "financial analysis|FP&A|budgeting and forecasting|variance analysis|management accounts|financial modeling|budgeting|forecasting|financial planning and analysis|P&L", "", "",
     "Financial planning and analysis: budgets, forecasts, variance analysis, financial models and management reporting."),
    ("auditing", "auditing", "internal audit|external audit|audit|SOX testing|controls testing|risk assessment|audit findings|internal controls", "", "",
     "Auditing: internal and external audits, testing controls, risk assessments, findings and remediation."),
    ("tax", "tax", "tax preparation|tax returns|tax compliance|corporate tax|sales tax|tax planning|tax accounting|income tax|VAT", "", "",
     "Tax: preparing returns, tax compliance and planning for individuals or companies."),
    ("banking", "banking", "retail banking|commercial banking|loan processing|lending|mortgage|credit analysis|underwriting|branch operations|teller|loan officer|deposits", "", "",
     "Banking: retail and commercial banking operations, lending, credit, underwriting, branch and teller work."),
    ("investment", "investment management", "portfolio management|wealth management|asset management|equity research|trading|financial planning|investment analysis|financial advisor|securities", "", "",
     "Investment: portfolio and wealth management, research, trading, financial advice, securities."),
    ("sales", "sales", "B2B sales|account management|business development|lead generation|cold calling|sales pipeline|closing deals|territory management|quota|upselling|inside sales|outside sales|sales targets|prospecting|client acquisition", "", "",
     "Sales: prospecting, pipeline, closing deals, account management, quotas and territory management."),
    ("customer-service", "customer service", "customer support|client relations|customer satisfaction|call center|help desk|customer care|complaint resolution|customer experience|technical support|client service", "", "",
     "Customer service and support: helping customers, resolving complaints and tickets, call centres, help desks."),
    ("project-management", "project management", "project delivery|project planning|project coordination|stakeholder management|PMO|project schedules|risk management|program management|project budgets|project lifecycle", "", "",
     "Project management: planning, scheduling, budgets, risks, stakeholders and delivery of projects and programmes."),
    ("product-management", "product management", "product roadmap|product strategy|product owner|roadmapping|feature prioritization|product discovery|user stories|product requirements|PRD|go-to-market", "", "",
     "Product management: roadmaps, requirements, prioritisation, discovery, working with engineering and design to ship products."),
    ("ux-design", "UX design", "user experience|UX research|user research|wireframes|prototyping|usability testing|interaction design|UI design|user interface design|user flows|design thinking", "", "",
     "UX/UI design: research, wireframes, prototypes, usability testing, interaction and interface design."),
    ("graphic-design", "graphic design", "visual design|branding|logo design|typography|layout design|print design|illustration|packaging design|brand identity|marketing collateral", "", "",
     "Graphic design: visual identity, branding, layouts, print and digital collateral, illustration."),
    ("event-planning", "event planning", "event management|event coordination|conferences|trade shows|banquets|weddings|event logistics|corporate events", "", "",
     "Event planning: organising conferences, trade shows, banquets, weddings and corporate events."),
    ("culinary", "culinary", "cooking|menu planning|menu development|food preparation|kitchen operations|line cook|sous chef|catering|baking|pastry|food safety|HACCP|ServSafe|plating|recipe development|kitchen staff|food cost", "", "",
     "Culinary work: cooking, menu planning, kitchen operations, food safety, catering, baking."),
    ("hospitality", "hospitality", "hotel operations|front desk|guest services|housekeeping|reservations|restaurant management|food and beverage|F&B|concierge|guest satisfaction", "", "",
     "Hospitality: hotel and restaurant operations, guest services, front desk, housekeeping, food and beverage."),
    ("patient-care", "patient care", "nursing|clinical care|bedside care|vital signs|medication administration|patient assessment|charting|phlebotomy|EMR|electronic medical records|EHR|triage|wound care|patient education|direct patient care|caregiving", "", "",
     "Patient care: nursing and clinical care, assessments, medications, charting in EMR/EHR systems, caregiving."),
    ("healthcare-administration", "healthcare administration", "medical billing|medical coding|ICD-10|CPT coding|insurance claims|prior authorization|medical records|practice management|revenue cycle|HIPAA|patient scheduling|medical office", "", "",
     "Healthcare administration: billing and coding, claims, records, scheduling, HIPAA, practice and revenue-cycle management."),
    ("teaching", "teaching", "classroom management|lesson planning|instruction|tutoring|student assessment|special education|IEP|curriculum|differentiated instruction|grading|student engagement|educator|teacher", "", "",
     "Teaching: classroom instruction, lesson planning, assessment, curriculum, special education, tutoring."),
    ("construction-management", "construction management", "construction|site supervision|subcontractors|blueprints|estimating|bidding|building codes|permits|general contractor|carpentry|electrical work|plumbing|HVAC|welding|site safety|construction projects", "", "",
     "Construction: site management, trades, estimating, subcontractors, codes and permits, safety."),
    ("engineering-design", "engineering design", "mechanical design|CAD design|product design|design reviews|tolerance analysis|FEA|finite element analysis|structural analysis|electrical design|circuit design|PCB design|schematics|prototyping hardware|GD&T", "", "",
     "Engineering design: mechanical, electrical and structural design, CAD, analysis, prototyping, design reviews."),
    ("manufacturing", "manufacturing", "production|continuous improvement|assembly line|machining|CNC|quality control|GMP|ISO 9001|production planning|shop floor|process improvement|manufacturing processes|plant operations", "production", "manufacturing|plant|assembly|line|factory|machining|shop floor|operators|shifts|equipment|output",
     "Manufacturing: production operations, process improvement, lean, quality control, plant and shop-floor work."),
    ("supply-chain", "supply chain", "logistics|procurement|purchasing|inventory management|warehouse operations|shipping and receiving|distribution|vendor management|demand planning|freight|fleet management|dispatch|inventory control|supplier management|order fulfillment", "", "",
     "Supply chain and logistics: procurement, inventory, warehousing, shipping, distribution, vendors and planning."),
    ("quality-assurance", "quality assurance", "QA|inspection|audits|corrective actions|CAPA|SOPs|ISO|validation|GxP|quality management|quality systems|defect tracking", "", "",
     "Quality assurance: inspections, audits, SOPs, corrective actions, quality systems and standards."),
    ("aviation", "aviation", "aircraft maintenance|flight operations|FAA|pilot|avionics|airline operations|air traffic|aircraft|flight|airport operations|A&P|aviation safety|flight crew", "", "",
     "Aviation: flight operations, aircraft maintenance, avionics, airline and airport operations, FAA regulations."),
    ("automotive", "automotive", "vehicle repair|auto repair|automotive technician|diagnostics|ASE certified|dealership|service advisor|brakes|engines|body shop|vehicles|auto parts", "", "",
     "Automotive: vehicle repair and diagnostics, dealership service, parts, technicians."),
    ("agriculture", "agriculture", "farming|crop management|livestock|irrigation|harvest|greenhouse|agronomy|farm operations|animal husbandry|pest management|crops|farm", "", "",
     "Agriculture: farming, crops, livestock, irrigation, harvests, agronomy."),
    ("fitness-and-wellness", "fitness training", "personal training|fitness|group fitness|nutrition coaching|strength training|wellness programs|exercise programs|yoga|personal trainer|fitness instructor|athletic training", "", "",
     "Fitness and wellness: personal and group training, exercise programmes, nutrition coaching."),
    ("legal", "legal", "litigation|legal research|contracts|contract drafting|legal drafting|paralegal|case management|court filings|attorney|counsel|depositions|discovery|regulatory affairs|legal documents|law firm|pleadings|contract review", "discovery", "litigation|court|legal|case|deposition|attorney|law|documents|filings|pleadings",
     "Legal: litigation, research, drafting contracts and pleadings, case management, regulatory affairs, paralegal work."),
    ("real-estate", "real estate", "property management|leasing|realtor|listings|tenant relations|property sales|escrow|closings|MLS|commercial real estate|residential real estate|properties|rental properties", "", "",
     "Real estate: sales and leasing, property management, tenants, listings, closings."),
    ("retail-operations", "retail operations", "store operations|merchandising|visual merchandising|cash handling|loss prevention|store management|shift supervision|planograms|apparel|fashion retail|buying|retail sales|cashier|stocking", "", "",
     "Retail: store operations, merchandising, cash handling, loss prevention, apparel and fashion retail."),
    ("media-production", "media production", "video production|video editing|photography|audio production|broadcast|post-production|motion graphics|animation|social media content|journalism|writing and editing|filming|videography|3D modeling", "", "",
     "Media production: video, photography, audio, animation, motion graphics, broadcast and post-production."),
    ("social-media", "social media", "social media management|community management|Instagram|Facebook|TikTok|LinkedIn marketing|influencer marketing|engagement growth|social channels|content scheduling", "", "",
     "Social media: managing channels and communities, content calendars, influencer and engagement campaigns."),
]


def build_rows() -> list[dict]:
    rows = []
    for slug, canonical, aliases, implies, ambiguous, context in S:
        rows.append(dict(kind="skill", slug=slug, canonical=canonical, aliases=aliases, implies=implies,
                         ambiguous=ambiguous, context=context, description=""))
    for slug, canonical, aliases, ambiguous, context, description in T:
        rows.append(dict(kind="topic", slug=slug, canonical=canonical, aliases=aliases, implies="",
                         ambiguous=ambiguous, context=context, description=description))
    return rows


def lint(rows: list[dict]) -> list[str]:
    problems = []
    slugs = {r["slug"] for r in rows}
    if len(slugs) != len(rows):
        problems.append("duplicate slugs")
    owner: dict[str, str] = {}
    for r in rows:
        forms = [r["canonical"]] + [a for a in r["aliases"].split("|") if a]
        for f in forms:
            key = f.lower()
            if key in owner and owner[key] != r["slug"]:
                problems.append(f"surface form {f!r} belongs to both {owner[key]} and {r['slug']}")
            owner[key] = r["slug"]
        for amb in [a for a in r["ambiguous"].split("|") if a]:
            if amb.lower() not in {x.lower() for x in forms}:
                problems.append(f"{r['slug']}: ambiguous form {amb!r} is not one of its surface forms")
            if not r["context"]:
                problems.append(f"{r['slug']}: ambiguous form {amb!r} but no context words")
        for imp in [i for i in r["implies"].split("|") if i]:
            if imp not in slugs:
                problems.append(f"{r['slug']}: implies unknown term {imp!r}")
            if imp == r["slug"]:
                problems.append(f"{r['slug']}: implies itself")
    return problems


def main() -> int:
    rows = build_rows()
    problems = lint(rows)
    if problems:
        print("vocab seed is inconsistent:\n  " + "\n  ".join(problems))
        return 1
    out = Path(__file__).resolve().parents[1] / "schema" / "vocab.csv"
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["kind", "slug", "canonical", "aliases", "implies", "ambiguous", "context", "description"])
        w.writeheader()
        w.writerows(rows)
    n_skill = sum(1 for r in rows if r["kind"] == "skill")
    n_topic = len(rows) - n_skill
    n_forms = sum(1 + (len(r["aliases"].split("|")) if r["aliases"] else 0) for r in rows)
    print(f"wrote {out}: {n_skill} skills, {n_topic} topics, {n_forms} surface forms")
    return 0


if __name__ == "__main__":
    sys.exit(main())
